// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// import 'firebase_options.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALcEgn3u0Q2OVGD2dBzv4noXGcn7CwfFk',
    appId: '1:256929510687:web:6056c793d0a3227b9f2c2a',
    messagingSenderId: '256929510687',
    projectId: 'sncapp-38380',
    authDomain: 'sncapp-38380.firebaseapp.com',
    storageBucket: 'sncapp-38380.appspot.com',
    measurementId: 'G-EEFT1DQVNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYi4-K5Bn_Kir9n4f_LGZd5QAlFrD73TA',
    appId: '1:256929510687:android:0a3ca87925f3cac39f2c2a',
    messagingSenderId: '256929510687',
    projectId: 'sncapp-38380',
    storageBucket: 'sncapp-38380.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgNao8fmE3f2rY5kS8M6wbdJZxMWlEiPM',
    appId: '1:256929510687:ios:5c6d557901934f6e9f2c2a',
    messagingSenderId: '256929510687',
    projectId: 'sncapp-38380',
    storageBucket: 'sncapp-38380.appspot.com',
    iosBundleId: 'com.example.sncapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgNao8fmE3f2rY5kS8M6wbdJZxMWlEiPM',
    appId: '1:256929510687:ios:5c6d557901934f6e9f2c2a',
    messagingSenderId: '256929510687',
    projectId: 'sncapp-38380',
    storageBucket: 'sncapp-38380.appspot.com',
    iosBundleId: 'com.example.sncapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALcEgn3u0Q2OVGD2dBzv4noXGcn7CwfFk',
    appId: '1:256929510687:web:c620e69544fe71039f2c2a',
    messagingSenderId: '256929510687',
    projectId: 'sncapp-38380',
    authDomain: 'sncapp-38380.firebaseapp.com',
    storageBucket: 'sncapp-38380.appspot.com',
    measurementId: 'G-ED3WD2R9P5',
  );

}